audit_header: false
title: The Valley of the Sun's Best Real Estate Training
description: Nate Martinez, a top Real Estate Agent in The Valley of the Sun, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: https://www.eventbrite.com/o/remax-professionals-17799574908
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
  - title: Agent Development Calendar
    url: /calendar/
  - title: Meet Our Owner
    url: /meet-our-owner/

client:
  name: Nate Martinez
  title:
  license_number:
  about_markdown: |
    Nate has been selling real estate in the Valley of the Sun for nearly thirty years. He is the co-owner of RE/MAX Professionals, founded in 2001 and has three valley locations in Glendale, Surprise, and Avondale.

    Nate believes in education and giving back to the real estate industry. His designations include ABR, CRS, GRI, CDPE, CIAS, CLHS, CRP, e-PRO and SFR Each year, Nate attends numerous seminars and training events across the country. As a guest speaker, Nate has been able to train hundreds of real estate professionals, while also learning from some of the best agents in the industry.
  market: Valley of the Sun
  brand: RE/MAX Professionals
  brokerage:
  address: 20241 N 67th Ave, Suite A1<br>Glendale, AZ 85308
  phone: 602-430-5226
  phone_type:
  phone2:
  phone2_type:
  email: NateM@Remax.net
  url: http://NatesHomes.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/ArizonaRealtorsMastermind/
  linkedin_url: http://www.linkedin.com/in/natemartinez
  gplus_url:
  youtube_url: https://www.youtube.com/user/natemartinez8
  twitter_url: http://twitter.com/NateMartinez
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/glendale-real-estate-careers/id1194698644?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#DC1C2E'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
