audit_header: false
title: The Valley of the Sun's Best Real Estate Training
description: Nate Martinez, a top Real Estate Agent in The Valley of the Sun, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: https://www.eventbrite.com/o/remax-professionals-17799574908
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
  - title: Agent Development Calendar
    url: /calendar/
  - title: Meet Our Owner
    url: /meet-our-owner/
  - title: Weekly Messages
    url: /weekly-messages/

client:
  name: Nate Martinez
  title:
  license_number:
  about_markdown: |
    Nate Martinez, REALTOR®, Owner, Team Leader, Master Coach, International Bestselling Author, Coach, ABR, CRS, GRI, e-PRO, CDPE, CIAS, CLHMS, CRP, and SFR

    Nate Martinez is the owner of RE/MAX Professionals, a multi-office franchise located in the greater Phoenix area and the owner of a Motto Mortgage franchise. The highlight of running his business and team is getting to work in the trenches every day with the love of his life and his adult children. In 2021, he co-authored an international bestselling book, 8 Ways to Dominate Any Real Estate Market with long-time business partner, team member and friend, Sarah Michelle Bliss.

    Nate passionately believes in the value of education, having trained hundreds of real estate professionals across the globe as a speaker and a coach. With more than thirty-five years in the real estate industry, he has been recognized with the Lifetime Achievement, Titan Team, Circle of Legends, and the Luminary of Distinction from RE/MAX. But with all these achievements, Nate’s focus has always been giving back to this industry and now focuses much of his time on helping agents discover their potential and ultimately live their best life.

    He is most proud of the charitable contributions of his agents to the Children’s Miracle Network and the support of their local Phoenix Children’s Hospital. In addition, he is proud to be ranked the number one brokerage in Arizona when it comes to production per agent.

    Outside of work, Nate enjoys golfing and spending quality time around the pool with his adult children and their spouses, his confidant Tonya, their daughter, Mila, and three grandchildren.
  market: Valley of the Sun
  brand: RE/MAX Professionals
  brokerage:
  address: 20241 N 67th Ave, Suite A1<br>Glendale, AZ 85308
  phone: 602-430-5226
  phone_type:
  phone2:
  phone2_type:
  email: NateM@Remax.net
  url: https://joinremaxprofessionalsaz.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/ArizonaRealtorsMastermind/
  linkedin_url: http://www.linkedin.com/in/natemartinez
  gplus_url:
  youtube_url: https://www.youtube.com/user/natemartinez8
  twitter_url: http://twitter.com/NateMartinez
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/glendale-real-estate-careers/id1194698644?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#DC1C2E'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
